#!/bin/sh -e

BUSYBOX_TAG="docker.io/library/busybox:stable"
BUSYBOX_PATH="/usr/share/vyos/busybox-stable.tar"
if [[ ! -f $BUSYBOX_PATH ]]; then
    skopeo copy --additional-tag "$BUSYBOX_TAG" "docker://$BUSYBOX_TAG" "docker-archive:/$BUSYBOX_PATH"
fi

TACPLUS_TAG="docker.io/lfkeitel/tacacs_plus:alpine"
TACPLUS_PATH="/usr/share/vyos/tacplus-alpine.tar"
if [[ ! -f $TACPLUS_PATH ]]; then
    skopeo copy --additional-tag "$TACPLUS_TAG" "docker://$TACPLUS_TAG" "docker-archive:/$TACPLUS_PATH"
fi
